# Generated by Django 5.1 on 2024-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=40)),
                ('comuna', models.CharField(max_length=100)),
                ('tienda', models.CharField(max_length=100)),
            ],
        ),
    ]
